name: Upload Python Package to PyPI

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Run Black Formatter throughout the codebase", "Ruff Linter"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      #- name: Version bump
      #  uses: monperrus/pyproject-bump-pypi@main
      #  with:
      #    file_to_bump: "./pyproject.toml"
      #    bump_type: "minor"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - run: pip install build
      - run: python -m build --wheel
      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
