name: Upload Python Package to PyPi

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Run Black Formatter throughout the codebase", "Ruff Linter"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Version bump
        uses: monperrus/pyproject-bump-pypi@main
        with:
          file_to_bump: "./pyproject.toml"
          bump_type: "minor"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
        run: |
          twine upload dist/*
